import { hmac } from "@noble/hashes/hmac";
import { sha256 } from "@noble/hashes/sha256";

export const REFRESH_TOKEN_BYTES = 32;
export const VERIFICATION_TOKEN_BYTES = 32;

function toBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function toHex(bytes: Uint8Array): string {
  let hex = "";
  for (const byte of bytes) {
    hex += byte.toString(16).padStart(2, "0");
  }
  return hex;
}

/** Generates a random opaque token, base64url-encoded (no padding). */
export function generateOpaqueToken(byteLength = 32): string {
  const bytes = crypto.getRandomValues(new Uint8Array(byteLength));
  return toBase64Url(bytes);
}

/**
 * Hashes a raw opaque token for storage-at-rest via HMAC-SHA256 with a
 * server-side pepper. Never plain SHA-256 — the pepper (a Worker secret,
 * never stored in D1) is what makes a D1-only leak useless to an attacker.
 */
export function hashToken(rawToken: string, pepper: string): string {
  const mac = hmac(sha256, new TextEncoder().encode(pepper), new TextEncoder().encode(rawToken));
  return toHex(mac);
}

/**
 * Reports the entropy, in bits, of a base64url-encoded token string,
 * assuming it was generated by `generateOpaqueToken`. Used only by tests to
 * assert the ≥256-bit entropy floor.
 */
export function tokenEntropyBits(token: string): number {
  const padLength = (4 - (token.length % 4)) % 4;
  const padded = token.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat(padLength);
  const byteLength = (padded.length / 4) * 3 - padLength;
  return byteLength * 8;
}
